---
# configure ansible engine and nodes with users and access

- hosts: all
  become: true
  vars:
    devops_public_key: ""
  tasks:
    - name: Set Hostname
      hostname:
        name: "{{ inventory_hostname }}"
 
    - name: install Packages
      yum:
       name:
         - vim
       state: present
 
    - name:
      file:
        path: /home/devops/.ssh
        state: directory
        owner: devops
        group: devops
        mode: 0700

    - name: Create authorized_keys if not exist
      copy:
       dest: /home/devops/.ssh/authorized_keys
       content: ""
       force: no
       owner: devops
       group: devops
       mode: '0600'
 
    - name: Copy Authorized keys to devops user
      blockinfile:
        path: /home/devops.ssh/authorized_keys
      blocke: "'{{ llokup('file', '/home/ec2-user/.ssh/authorized_keys') }}"

    - name: Copy Sample Inventory to devops home
      copy:
        src: '/home/ec2-user/inventory'
        dest: "/home/devops/inventory"
        mode: '0755'
        owner: devops
        group: devops
      when: inventory_hostname == 'ansible-engine'
   
    - name: copy ansible.cfg to devops home
      copy:
        src: '/home/ec2-user/ansible.cfg'
        dest: "/home/devops/ansible.cfg"
        mode: '0755'
        owner: devops
        group: devops
      when: inventory_hostname == 'ansible-engine'

    - name: update /etc/hosts
      lineinfile:
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}"
        path: /etc/hosts
      loop: "{{ groups['all'] }}"
      #ignore_errors: yes

    - name: Generate an OpenSSH keypair 2048 bits
      openssh_keypair:
        path: '/home/ec2-user/.ssh/id_rsa'
        size:
        force:
        owner:
        group:
      delegate_to: ansible-engine
      when: inventory_hostname == 'ansible-engine'

    - name: Copy SSH Private key to devops user #Is this needed?!
      copy:
        src: "/home/ec2-user/.ssh/id_rsa"
        dest: "/home/devops/.ssh/id_rsa"
        owner: devops
        group: devops
        mode: '0600'
        force: yes
      when: inventory_hostname == 'ansible-engine'

    - name: Copy SSH Public key to devops user
      copy:
        src: "/home/ec2-user/.ssh/id_rsa.pub"
        dest: "/home/devops/.ssh/id_rsa.pub"
        owner: devops
        group: devops
        mode: '0644'
        force: yes
      when: inventory_hostname == 'ansible-engine'
 
    - name: Fetch the Public key Content
      become: false
      set_fact:
        devops_public_key: "{{ lookup('file', '/home/ec2-user/.ssh/id_rsa.pub') }}"
      delegate_to: ansible-engine
      when: inventory_hostname == 'ansible-engine'

    - name: Add Ansible Engine keys to authorized_keys of nodes
      authorized_key:
        user: devops
        devopsstate: present
        key: "{{ hostvars['ansible-engine']['devops_public_key'] }}"

    - name: Disable password login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present

    - name: Restart sshd
      service:
        name: sshd
        state: restarted

    - name: Clen up inventory in devops home
      lineinfile:
        dest: /home/devops/inventory
        regexp: "^ansible_ssh_extra_args"
        state: absent
      when: inventory_hostname == 'ansible-engine'
